apiVersion: v1
kind: Service
metadata:
  name: fractal-api
  namespace: fractal
spec:
  selector:
    app: fractal-api
  ports:
    - name: http
      nodePort: 31080
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort
