apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-fractal-api
  namespace: fractal
data:
  FRACTAL_CORE_SERVICE: "http://fractal-core.fractal:5000"
  FRACTAL_DB_HOST: "postgis.fractal"
  FRACTAL_DB_URL: "jdbc:postgresql://postgis.fractal:5432/fractal_api_db"
  FRACTAL_INPUT_FILEPATH: "/fractal/data/input/"
  FRACTAL_MQ_CREATE_CITY: "fractal.create.city.queue"
  FRACTAL_MQ_PROCESS_QUEUE: "fractal.start.process.queue"
  FRACTAL_MQ_URL: "tcp://active-mq.brokers:61616"
  FRACTAL_OUTPUT_FILEPATH: "/fractal/data/output/"
  FRACTAL_UI_HOST: "fractal-webui.fractal"
  FRACTAL_POOL_SIZE: "1"
  FRACTAL_ETL_SERVICE: "http://192.168.2.100:8085"
  TZ: "America/Sao_Paulo"
  FRACTAL_AIRFLOW_PASSWORD: "airflow"
  FRACTAL_AIRFLOW_USER: "airflow"
  FRACTAL_API_PASSWORD: "root"
  FRACTAL_API_USERNAME: "fractal_api"
  FRACTAL_MQ_PASSWORD: "admin"
  FRACTAL_MQ_USERNAME: "admin"
