apiVersion: apps/v1
kind: Deployment
metadata:
  name: fly-webui
  namespace: fractal
  labels:
    app: fly-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fly-webui
  template:
    metadata:
      name: fly-webui
      labels:
        app: fly-webui
    spec:
      containers:
        - name: fly-webui
          image: cezaodabahia/fly:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256M"
              cpu: "50m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
