apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-api-core
  namespace: fractal
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeName: pv-fractal-data
  storageClassName: local-storage-rwm
