apiVersion: v1
kind: Service
metadata:
  name: fractal-mfe
  namespace: fractal
spec:
  selector:
    app: fractal-mfe
  ports:
    - name: http
      nodePort: 31000
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
