apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-volume-claim
  namespace: fractal
  labels:
    app: postgis
    project: fractal
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
