apiVersion: v1
kind: Service
metadata:
  name: postgis
  namespace: fractal
  labels:
    app: postgis
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30433
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
