apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  namespace: fractal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
        project: fractal
    spec:
      containers:
        - name: postgis
          image: postgis/postgis:16-3.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgis-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgis-volume-claim
