apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: keycloak
  labels:
    app: postgres-kc
data:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak_user
  POSTGRES_PASSWORD: keycloak_super_secure_password
