apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: keycloak
  labels:
    type: local
    app: postgres-kc
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres_kc
