apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: active-mq
    project: fractal
  name: active-mq
  namespace: fractal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: active-mq
  template:
    metadata:
      labels:
        app: active-mq
    spec:
      containers:
        - name: active-mq
          image: apache/activemq-classic:5.18.6
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 400m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
