apiVersion: v1
kind: Service
metadata:
  labels:
    app: active-mq
    project: fractal
  name: active-mq
  namespace: fractal
spec:
  ports:
    - name: dashboard
      port: 8161
      protocol: TCP
      targetPort: 8161
      nodePort: 30161
    - name: openwire
      port: 61616
      protocol: TCP
      targetPort: 61616
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: stomp
      port: 61613
      protocol: TCP
      targetPort: 61613
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    app: active-mq
  type: LoadBalancer
